name: Deploy to Railway

on:
  push:
    branches:
      - main  # автоматически деплоить на Railway при пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t vizurth/urlshortener:latest -f docker/Dockerfile .
          docker push vizurth/urlshortener:latest

      - name: Trigger Railway Deployment
        run: |
          curl -X POST \
            -d '{"branch": "main"}' \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_API_KEY }}" \
            "https://api.railway.app/v1/projects/YOUR_PROJECT_ID/deploys"
