name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Start services with docker-compose
        run: docker-compose up -d --build

      - name: Wait for services to be ready
        run: |
          echo "Waiting for Postgres..."
          for i in {1..30}; do
            if docker exec postgres_container_for_url_shortener pg_isready -U root; then
              echo "Postgres is ready!"
              break
            fi
            sleep 2
          done
      - name: View application logs
        run: docker logs url_shortener

      - name: Stop services
        if: always()
        run: docker-compose down
